city_country_data_1 = [
    ("Split", "Croatia"),
    ("Củ Chi", "Vietnam"),
    ("Kuala Lumpur", "Malaysia"),
    ("Budapest", "Hungary"),
    ("San Francisco", "California (USA)"),
    ("Marsa Alam", "Egypt"),
    ("Siem Reap", "Cambodia"),
    ("Milano", "Italy"),
    ("Dubai", "United Arab Emirates"),
    ("Dahab", "Egypt"),
    ("Singapore", "Singapore"),
    ("Kimana", "Kenya"),
    ("Nusa Penida", "Indonesia"),
    ("Havana", "Cuba"),
    ("Lyon", "France"),
    ("Montpellier", "France"),
    ("Jakarta", "Indonesia"),
    ("Ho Chi Minh", "Vietnam"),
    ("Bratislava", "Slovakia"),
    ("Bali", "Indonesia"),
    ("Fuerteventura", "Canary Islands (Spain)"),
    ("Doha", "Qatar"),
    ("Las Vegas", "Nevada (USA)"),
    ("Alberobello", "Italy"),
    ("Rhodes", "Greece"),
    ("Cayo Santa María", "Cuba"),
    ("Berlin", "Germany"),
    ("Seligman", "Arizona (USA)"),
    ("Barcelona", "Spain"),
    ("Tatranská Lomnica", "Slovakia"),
    ("Cinque Terre", "Italy"),
    ("Sal", "Cabo Verde"),
    ("Batu Caves", "Malaysia"),
    ("Rijeka", "Croatia"),
    ("Vienna", "Austria"),
    ("Antalya", "Turkey"),
    ("London", "United Kingdom"),
    ("Los Angeles", "California (USA)"),
    ("Zittau", "Germany"),
    ("Genova", "Italy"),
    ("Sharm El Sheikh", "Egypt"),
    ("Cairo", "Egypt"),
    ("Plitvička Jezera", "Croatia"),
    ("Lago di Garda", "Italy"),
    ("Međugorje", "Bosnia and Herzegovina"),
    ("Jesolo", "Italy"),
    ("Grand Canyon", "Arizona (USA)"),
    ("Crete", "Greece"),
    ("Hollywood", "California (USA)"),
    ("Špindlerův Mlýn", "Czech Republic"),
    ("Etna", "Italy"),
    ("Prague", "Czech Republic"),
    ("Dresden", "Germany"),
    ("Leipzig", "Germany"),
    ("Geneva", "Switzerland"),
    ("Liberec", "Czech Republic"),
    ("Innsbruck", "Austria"),
    ("Venice", "Italy"),
    ("Hoover Dam", "Arizona (USA)"),
]


city_image_paths_1 = {
    "Split": "split.png",
    "Củ Chi": "cu_chi.png",
    "Kuala Lumpur": "kuala_lumpur.png",
    "Budapest": "budapest.png",
    "San Francisco": "san_francisco.png",
    "Marsa Alam": "marsa_alam.png",
    "Siem Reap": "siem_reap.png",
    "Milano": "milano.png",
    "Dubai": "dubai.png",
    "Dahab": "dahab.png",
    "Singapore": "singapore.png",
    "Kimana": "kimana.png",
    "Nusa Penida": "nusa_penida.png",
    "Havana": "havana.png",
    "Lyon": "lyon.png",
    "Montpellier": "montpellier.png",
    "Jakarta": "jakarta.png",
    "Ho Chi Minh": "ho_chi_minh.png",
    "Bratislava": "bratislava.png",
    "Bali": "bali.png",
    "Fuerteventura": "fuerteventura.png",
    "Doha": "doha.png",
    "Las Vegas": "las_vegas.png",
    "Alberobello": "alberobello.png",
    "Rhodes": "rhodes.png",
    "Cayo Santa María": "cayo_santa_maria.png",
    "Berlin": "berlin.png",
    "Seligman": "seligman.png",
    "Barcelona": "barcelona.png",
    "Tatranská Lomnica": "tatranska_lomnica.png",
    "Cinque Terre": "cinque_terre.png",
    "Sal": "sal.png",
    "Batu Caves": "batu_caves.png",
    "Rijeka": "rijeka.png",
    "Vienna": "vienna.png",
    "Antalya": "antalya.png",
    "London": "london.png",
    "Los Angeles": "los_angeles.png",
    "Zittau": "zittau.png",
    "Genova": "genova.png",
    "Sharm El Sheikh": "sharm_el_sheikh.png",
    "Cairo": "cairo.png",
    "Plitvička Jezera": "plitvicka_jezera.png",
    "Lago di Garda": "lago_di_garda.png",
    "Međugorje": "medjugorje.png",
    "Jesolo": "jesolo.png",
    "Grand Canyon": "grand_canyon.png",
    "Crete": "crete.png",
    "Hollywood": "hollywood.png",
    "Špindlerův Mlýn": "spindleruv_mlyn.png",
    "Etna": "etna.png",
    "Prague": "prague.png",
    "Leipzig": "leipzig.png",
    "Dresden": "dresden.png",
    "Geneva": "geneva.png",
    "Liberec": "liberec.png",
    "Innsbruck": "innsbruck.png",
    "Venice": "venice.png",
    "Hoover Dam": "hoover_dam.png",
}


city_country_data_2 = {
    ("Warsaw", "Poland"),
    ("Taormina", "Italy"),
    ("Dubrovnik", "Croatia"),
    ("Belek", "Turkey"),
    ("Bari", "Italy"),
    ("Matera", "Italy"),
    ("Kleinwelka", "Germany"),
    ("Cracow", "Poland"),
    ("Isla Nublar", "Costa Rica"),
    ("Gdańsk", "Poland"),
    ("Wrocław", "Poland"),
}


city_image_paths_2 = {"Warsaw": "warsaw.png",
                      "Taormina": "taormina.png",
                      "Dubrovnik": "dubrovnik.png",
                      "Belek": "belek.png",
                      "Bari": "bari.png",
                      "Matera": "matera.png",
                      "Kleinwelka": "kleinwelka.png",
                      "Cracow": "cracow.png",
                      "Isla Nublar": "isla_nublar.png",
                      "Gdańsk": "gdansk.png",
                      "Wrocław": "wroclaw.png"
                      }